version: '3'
services:
  front:
    build: ./episen-sca-kto-front/.
    container_name: "ordersfront"
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
    links:
      - "back:orders-back"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M
        reservations:
          cpus: "0.5"
          memory: 100M
  back:
    build: ./episen-sca-kto-backend/.
    container_name: "ordersback"
    hostname: orders-back
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
    volumes:
      - back-data:/logs
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 300M
        reservations:
          cpus: "0.5"
          memory: 200M
volumes:
  back-data:
