version: '3'
services:
  episen-sca-kto-front:
    build: ./episen-sca-kto-front/.
    container_name: "ordersfront"
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
    links:
      - "episen-sca-kto-backend:orders-back"
    volumes:
      - vol-episen-sca-kto-front:/logsFront
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M
        reservations:
          cpus: "0.5"
          memory: 100M
      replicas: 2
      restart_policy:
        condition: on-failure
  episen-sca-kto-backend:
    build: ./episen-sca-kto-backend/.
    container_name: "ordersback"
    hostname: orders-back
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
    volumes:
      - vol-episen-sca-kto-backend:/logs
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 300M
        reservations:
          cpus: "0.5"
          memory: 200M
      replicas: 2
      restart_policy:
        condition: on-failure
volumes:
  vol-episen-sca-kto-backend:
  vol-episen-sca-kto-front:
