version: '3.4'
services:
  episen-sca-kto-front:
    build: ./episen-sca-kto-front/.
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
    links:
      - "episen-sca-kto-backend:orders-back"
    volumes:
      - vol-episen-sca-kto-front:/logsFront
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 0
        delay: 10s
      resources:
        limits:
          cpus: "1"
          memory: 200M
        reservations:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: on-failure
  episen-sca-kto-backend:
    build: ./episen-sca-kto-backend/.
    hostname: orders-back
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
    volumes:
      - vol-episen-sca-kto-backend:/logs
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 0
        delay: 10s
      resources:
        limits:
          cpus: "1"
          memory: 300M
        reservations:
          cpus: "0.5"
          memory: 200M
      restart_policy:
        condition: on-failure
volumes:
  vol-episen-sca-kto-backend:
  vol-episen-sca-kto-front:
